apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: nodejs-hello-world
    env: production
    managed-by: kubectl
  annotations:
    description: "Configuration for Node.js Hello World app"
data:
  config.json: |
    {
      "setting1": "value1",
      "setting2": "value2"
    }
